### PR TITLE
Track IO write status, and selectively terminate session on timeout

### PR DESCRIPTION
**Pull request by raulk**
Simplified implementation of #10.

### CODE REVIEW

**Comment by raulk** [comment]
@Stebalien this is WIP. I realised that waiting for `ConnWriteTimeout` after we've already waited for the stream timeout is too much waiting. Both timeouts should compete, with the stream timeout just returning an error, and the connection write timeout aborting the connection if a partial write took place.

I'm trying to add another `compareAndSwap` here: https://github.com/whyrusleeping/yamux/pull/11/files#diff-f2fccfb96064097b73fbe8eeae3703eeR397, to avoid terminating the connection unless a partial write has taken place. 

But simulating this circumstance in test code is pretty tough. Working on it. In the interim, I'd appreciate your thoughts.

**Comment by Stebalien** [comment]
> I realised that waiting for ConnWriteTimeout after we've already waited for the stream timeout is too much waiting. Both timeouts should compete, with the stream timeout just returning an error, and the connection write timeout aborting the connection if a partial write took place.

I don't think we want to do this. The *connection* write timeout dictates how long a *single* write should take. Really, I'm already worried that some individual writes will can take longer than 10s under normal circumstances. If start the timer in parallel, we'll be waiting on other parallel writes to other streams as well.

**Comment by Stebalien** [comment]
However, this looks like a *very* clean change. Awesome!

**Comment by Stebalien** [comment]
> But simulating this circumstance in test code is pretty tough. Working on it. In the interim, I'd appreciate your thoughts.

I'm not *that* concerned about this. Testing is important but stuff like this is best caught by fuzzing (which I assume we'll get once we get a libp2p daemon and a testing framework).

**Comment by raulk** [comment]
> If start the timer in parallel, we'll be waiting on other parallel writes to other streams as well.

You're right. I overlooked this. Working on another iteration. Hopefully the final one ;-)

**Comment by raulk** [comment]
The challenge is that the stream deadline might be nil (user hasn't set one), or the write could be a control message (e.g. window update), in which case the stream deadline should not apply. We'd need to fall back safely to the connection write timeout.

I'm cooking a solution up, which hopefully will convince us.

**Comment by raulk** [comment]
@Stebalien I'm feeling pretty good about this last iteration. Here's the final algo (also in the commit message):

```
t1: stream deadline, falling back to the connection write timeout if no
deadline has been set, or if a control message is being sent.

Behaviour:
* If t1 fires before the write is queued, return an error to the caller.
* If t1 fires after the write is queued, attempt to abort the write if
it's still queued:
  - If successful, return an error to the caller.
  - If unsuccessful, and a stream deadline had been set, give the
  connection a grace period equal to the connection write timeout. If
  the grace period elapses without the write finishing, terminate the
  connection immediately.
  - If unsuccessful, and a stream deadline had not been set, or this was
  a control message, terminate the connection immediately.
```

I've basically implemented what you suggested in #10, with the nuance that for writes without a stream write deadline (i.e. control messages, or where the user has not set one), my total wait time is the connection write timeout; no compounding.

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
This is much better. I'm still a bit worried about the automatically timing out when the user hasn't requested it but, well, yamux already does that. I'll open an issue to discuss.

**Pull request merged**
